### ISSUE TITLE
Add Web Accessibility (a11y) Standards and Why They Are Important in HTML Section

### ISSUE THREAD

**Issue by iamharnad** [shrutikapoor08/Learn-Web-Dvelopment-Checklist#13]
It is important that the Web be accessible to everyone in order to provide equal access and equal opportunity to people with disabilities. That is, the accessibility barriers to print, audio, and visual media can be much more easily overcome through Web technologies.

**Comment by Neha** [comment]
Can I take this? @shrutikapoor08  😍😊

**Comment by cheralathann** [comment]
#10 Already added

**Comment by shrutikapoor08** [comment]
Thanks you all! Love all the contributions
