### ISSUE TITLE
Add basics of UX terminology 

### ISSUE THREAD

**Issue by Neha** [shrutikapoor08/Learn-Web-Dvelopment-Checklist#7]
Add basics of UX terminology a web developer should be aware of:

- Tools UX use such as Sketch, Figma, Photoshop
- Style Guidelines
- Consistency between colors, and other values
- Font Units
- Images, GIFs, etc.
- Animations

**Comment by shrutikapoor08** [comment]
Would you add it as a PR in the Step Up section?

**Comment by Neha** [comment]
Would love to 👍

**Comment by Neha** [comment]
PR raised.

**Comment by shrutikapoor08** [comment]
Thanks a lot @Neha ! I really appreciate your contributions ❤️
